# Generated by Django 5.1.6 on 2025-03-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='partner')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='ourcontact',
            options={'verbose_name_plural': 'Our Contacts'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name_plural': 'Social Media'},
        ),
        migrations.AlterModelOptions(
            name='workinghours',
            options={'verbose_name_plural': 'Working Hours'},
        ),
    ]
