# Generated by Django 5.1.6 on 2025-03-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_partner_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='offer_percent',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
