# Generated by Django 5.1.6 on 2025-03-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(default='Customer', max_length=100),
        ),
    ]
