# Generated by Django 5.1.6 on 2025-03-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_testimonial_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
