# Generated by Django 5.1.6 on 2025-03-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workinghours',
            old_name='friday',
            new_name='monday_to_friday_closing_time',
        ),
        migrations.RenameField(
            model_name='workinghours',
            old_name='monday',
            new_name='monday_to_friday_opening_time',
        ),
        migrations.RenameField(
            model_name='workinghours',
            old_name='saturday',
            new_name='saturday_closing_time',
        ),
        migrations.RenameField(
            model_name='workinghours',
            old_name='sunday',
            new_name='saturday_opening_time',
        ),
        migrations.RemoveField(
            model_name='workinghours',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='workinghours',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='workinghours',
            name='wednesday',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
