# Generated by Django 5.1.6 on 2025-03-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_rename_friday_workinghours_monday_to_friday_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
