# Generated by Django 5.1.6 on 2025-03-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_remove_product_gallery_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
